services:
  multi-svc-env:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/home/vscode/.aws:ro
    # environment:
    user: 1000:1000
    privileged: true
    entrypoint: ["sh", "-c", "while sleep 1000; do :; done"]