FROM llwydev/vsc-base-images:v1.0.0

# COPY ./config/aws_config.sh /tmp/aws_config.sh
# COPY ./config/.env /tmp/.env

# USER root

# RUN chmod +x /tmp/aws_config.sh

# RUN /tmp/aws_config.sh

# USER vscode