services:
  dev-container:
    container_name: python-env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/home/vscode/.aws:ro
      - db_data:/var/lib/postgresql/data:ro
    environment:
      - PYTHONUNBUFFERED=1
      - SHELL=/bin/bash
    working_dir: /workspace
    user: vscode
    entrypoint: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
    networks:
      - dev-net

  database:
    container_name: postgresql
    image: bitnami/postgresql:17 # pulling local image
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev-net
    depends_on:
      - dev-container

  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.11 # pulling local image
    volumes:
      - ./terraform:/workspace
    working_dir: /workspace
    entrypoint: ["sh", "-c", "while true; do sleep 1000; done"]
    networks:
      - dev-net
    depends_on:
      - dev-container

volumes:
  db_data:

networks:
  dev-net:
    driver: bridge
