FROM llwydev/vcd-python:base AS base-image

# COPY .env/ /tmp/.env

# FROM bitnami/postgresql:17

# COPY --from=base-image /tmp/.env /tmp/.env

# ENV POSTGRES_USER=${POSTGRES_USER}
# ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
# ENV POSTGRES_DB=${POSTGRES_DB}